# Generated by Django 5.1.6 on 2025-03-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_payment_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="session_id",
        ),
    ]
