version: "3.9"


services:
  web:
    build: .
    env_file:
      - .env
    command: sh -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    expose:
      - 6379

  celery:
    build: .
    env_file:
      - .env
    command: poetry run celery -A config worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - web


  celery-beat:
    build: .
    command: poetry run celery -A config beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - web
    env_file:
      - .env


networks:
  default:


volumes:
  postgres_data:
  redis-data:
