version: "3.9"


services:
  web:
    build: .
    env_file:
      - .env
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:17.4
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  default:


volumes:
  postgres_data:
