version: "3.9"


services:
  web:
    build: .
    env_file:
      - .env
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:17.4
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    command: ["redis-server"]
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  celery:
    build: .
    command: poetry run celery -A config worker -l INFO
    depends_on:
      - redis

  celery-beat:
    build: .
    command: poetry run celery -A config beat -l INFO
    depends_on:
      - redis
      - celery


networks:
  default:


volumes:
  postgres_data:
  redis-data:
