# Generated by Django 5.1.6 on 2025-02-10 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="img_course/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="materials.course"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="img_lesson/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
