# Generated by Django 5.1.8 on 2025-04-05 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_course_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 5, 9, 32, 33, 897282, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
